# Generated by Django 3.1.3 on 2020-11-29 16:40

from django.db import migrations, models

import quantityfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "height",
                    quantityfield.fields.IntegerQuantityField(
                        base_units="millimeter", unit_choices=["millimeter"]
                    ),
                ),
                (
                    "width",
                    quantityfield.fields.QuantityField(
                        base_units="finger", unit_choices=["millimeter", "meter"]
                    ),
                ),
                (
                    "length",
                    quantityfield.fields.QuantityField(
                        base_units="meter", unit_choices=["meter"]
                    ),
                ),
                (
                    "volume",
                    quantityfield.fields.QuantityField(
                        base_units="liter", null=True, unit_choices=["liter"]
                    ),
                ),
            ],
        ),
    ]
